// @ts-nocheck
import { default as __fd_glob_68 } from "../content/docs/rendering/meta.json?collection=meta"
import { default as __fd_glob_67 } from "../content/docs/routing/meta.json?collection=meta"
import { default as __fd_glob_66 } from "../content/docs/production/meta.json?collection=meta"
import { default as __fd_glob_65 } from "../content/docs/layout/meta.json?collection=meta"
import { default as __fd_glob_64 } from "../content/docs/getting-started/meta.json?collection=meta"
import { default as __fd_glob_63 } from "../content/docs/forms/meta.json?collection=meta"
import { default as __fd_glob_62 } from "../content/docs/data-fetching/meta.json?collection=meta"
import { default as __fd_glob_61 } from "../content/docs/database/meta.json?collection=meta"
import { default as __fd_glob_60 } from "../content/docs/crud/meta.json?collection=meta"
import { default as __fd_glob_59 } from "../content/docs/api/meta.json?collection=meta"
import { default as __fd_glob_58 } from "../content/docs/authentication/meta.json?collection=meta"
import { default as __fd_glob_57 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_56 from "../content/docs/rendering/when-to-use.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/rendering/use-client-boundary.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/rendering/server-component.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/rendering/index.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/rendering/composition-pattern.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/rendering/client-component.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/routing/nested-route.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/routing/navigation.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/routing/index.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/routing/dynamic-route.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/routing/basic-routing.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/production/index.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/layout/shared-layout.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/layout/root-layout.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/layout/nested-layout.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/layout/index.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/forms/validation.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/forms/use-server-directive.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/forms/use-action-state.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/forms/server-actions.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/forms/revalidation-redirect-security.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/forms/pending-state.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/forms/index.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/forms/form-basics.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/getting-started/what-is-nextjs.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/getting-started/project-structure.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/getting-started/nextjs-vs-react-vite.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/database/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/crud/route-design.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/crud/loading-error-state.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/crud/list-and-detail.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/crud/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/crud/employee-case-study.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/crud/edit-employee.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/crud/delete-employee.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/crud/data-layer.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/crud/create-employee.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/data-fetching/revalidation.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/data-fetching/not-found.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/data-fetching/loading-ui.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/data-fetching/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/data-fetching/fetch-api.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/data-fetching/error-handling.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/data-fetching/dynamic-data.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/data-fetching/caching.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/data-fetching/async-server-component.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/authentication/index.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/api/status-error.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/api/route-handler.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/api/request-response.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/api/request-body.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/api/index.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/api/http-method.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/api/dynamic-query.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/api/caching-cors.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/index.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();

export const docs = await create.doc("docs", "content/docs", {"index.mdx": __fd_glob_0, "api/caching-cors.mdx": __fd_glob_1, "api/dynamic-query.mdx": __fd_glob_2, "api/http-method.mdx": __fd_glob_3, "api/index.mdx": __fd_glob_4, "api/request-body.mdx": __fd_glob_5, "api/request-response.mdx": __fd_glob_6, "api/route-handler.mdx": __fd_glob_7, "api/status-error.mdx": __fd_glob_8, "authentication/index.mdx": __fd_glob_9, "data-fetching/async-server-component.mdx": __fd_glob_10, "data-fetching/caching.mdx": __fd_glob_11, "data-fetching/dynamic-data.mdx": __fd_glob_12, "data-fetching/error-handling.mdx": __fd_glob_13, "data-fetching/fetch-api.mdx": __fd_glob_14, "data-fetching/index.mdx": __fd_glob_15, "data-fetching/loading-ui.mdx": __fd_glob_16, "data-fetching/not-found.mdx": __fd_glob_17, "data-fetching/revalidation.mdx": __fd_glob_18, "crud/create-employee.mdx": __fd_glob_19, "crud/data-layer.mdx": __fd_glob_20, "crud/delete-employee.mdx": __fd_glob_21, "crud/edit-employee.mdx": __fd_glob_22, "crud/employee-case-study.mdx": __fd_glob_23, "crud/index.mdx": __fd_glob_24, "crud/list-and-detail.mdx": __fd_glob_25, "crud/loading-error-state.mdx": __fd_glob_26, "crud/route-design.mdx": __fd_glob_27, "database/index.mdx": __fd_glob_28, "getting-started/index.mdx": __fd_glob_29, "getting-started/nextjs-vs-react-vite.mdx": __fd_glob_30, "getting-started/project-structure.mdx": __fd_glob_31, "getting-started/what-is-nextjs.mdx": __fd_glob_32, "forms/form-basics.mdx": __fd_glob_33, "forms/index.mdx": __fd_glob_34, "forms/pending-state.mdx": __fd_glob_35, "forms/revalidation-redirect-security.mdx": __fd_glob_36, "forms/server-actions.mdx": __fd_glob_37, "forms/use-action-state.mdx": __fd_glob_38, "forms/use-server-directive.mdx": __fd_glob_39, "forms/validation.mdx": __fd_glob_40, "layout/index.mdx": __fd_glob_41, "layout/nested-layout.mdx": __fd_glob_42, "layout/root-layout.mdx": __fd_glob_43, "layout/shared-layout.mdx": __fd_glob_44, "production/index.mdx": __fd_glob_45, "routing/basic-routing.mdx": __fd_glob_46, "routing/dynamic-route.mdx": __fd_glob_47, "routing/index.mdx": __fd_glob_48, "routing/navigation.mdx": __fd_glob_49, "routing/nested-route.mdx": __fd_glob_50, "rendering/client-component.mdx": __fd_glob_51, "rendering/composition-pattern.mdx": __fd_glob_52, "rendering/index.mdx": __fd_glob_53, "rendering/server-component.mdx": __fd_glob_54, "rendering/use-client-boundary.mdx": __fd_glob_55, "rendering/when-to-use.mdx": __fd_glob_56, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_57, "authentication/meta.json": __fd_glob_58, "api/meta.json": __fd_glob_59, "crud/meta.json": __fd_glob_60, "database/meta.json": __fd_glob_61, "data-fetching/meta.json": __fd_glob_62, "forms/meta.json": __fd_glob_63, "getting-started/meta.json": __fd_glob_64, "layout/meta.json": __fd_glob_65, "production/meta.json": __fd_glob_66, "routing/meta.json": __fd_glob_67, "rendering/meta.json": __fd_glob_68, });